version: '3'

services:
  odoo:
    image: odoo:16.0
    ports:
      - "8069:8069"
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - PGDATA=/var/lib/postgresql/data
    depends_on:
      - db
    volumes:
      - ./Data:/var/lib/odoo
      - ./../Addons:/mnt/extra-addons

  db:
    image: postgres:12
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_DB=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./Data/db:/var/lib/postgresql/data/pgdata

volumes:
  odoo_data:
  odoo_db_data:
